### PR TITLE
Go1: style changes

### PR DESCRIPTION
**Pull request by mpl**
Hi,

How do you want to go about this? It's mainly cosmetic/style changes that Brad made, and I was able to merge your latest changes cleanly back in without a problem.
Do you want us to do some sort of rebasing before so you have a "neater" history, or do you want to do this yourself, or else ?
Just tell me.

Hmm I've just noticed we don't want our import path changes to end up in your repo. But I suppose you can pick what commits you want to pull from the fork, right?

Cheers,
Mathieu

### CODE REVIEW

**Comment by rwcarlsen** [comment]
I'll take a look at it, add a commit changing import paths back, and merge --no-ff back into go1 branch (to keep go1 history clean). Happy thanksgiving.

**Comment by mpl** [comment]
I do no think that would do what you want it to (--no-ff) since our go1 branch (which is the one concerned with this pull request) is already merged back with your changes.

I've changed the paths back anyway so you can have an easier look at the diff.

**Comment by mpl** [comment]
We should figure out a workflow that works well for you for next time too.

**Comment by rwcarlsen** [comment]
I often rebase simpler sets of changes onto HEAD before merging - we could
do that.  The merge --no-ff does keep go1 branch's "first parent" history
clean - which is my primary concern.  However, I am a novice developer and
am open to other workflow suggestions.

**Comment by mpl** [comment]
Ok. since this is an easy patch anyway, I'll redo it from a fresh pull of your go-1 branch and pack it all in a single rebased commit that you can easily merge afterwards.

I think for the next times, I should avoid syncing our changes back to your go-1 branch myself, and let you do the rebasing & merging, that might be simpler.

**Pull request closed without merging**
