### PR TITLE
Don't allocate buffers for huge tag offsets

### PR DESCRIPTION
**Pull request by jbardin**
- There seems to be a relatively common corrupt tag which has an offset
  of MaxUint32. This is probably not a valid offset, so return early
  before we allocate allocate a slice this large.
- Fixes issue #20

### CODE REVIEW

**Comment by jbardin** [comment]
Added another proposed addition, which reads tag values into a `bytes.Buffer` so we don't try and allocate a `[]byte` upfront when the value may be too large.

**Comment by rwcarlsen** [comment]
Looks good.  Do you have an image that exhibits the problem that could be used as a test?

**Comment by jbardin** [comment]
(add style changes per bradfitz's comments, and squashed commits)

@rwcarlsen: I have a couple jpegs that can trigger this, but they don't really fit into the tiff tests. I could write them into the /exif tests, or just send them along to you if you want to make some synthetic tests out of the exif structure. Each jpeg is still 173793 after stripping the image down to 8x8. I haven't found a convenient way to write bad exif data.

**Comment by rwcarlsen** [comment]
I agree they should go in the /exif tests.  In the past, I've truncated
images after the jpeg app1 section to make them smaller.  This has worked
well since goexif doesn't read beyond it.

**Comment by jbardin** [comment]
Added files and tests to /exif

**Comment by rwcarlsen** [comment]
Could you make an `./exif/corrupt` directory and put the images in there?  I anticipate the corrupt image collection growing in the future as the exif package becomes more robust.

**Comment by jbardin** [comment]
moved test jpegs into `./exif/corrupt`

**Comment by jbardin** [comment]
now also fixes issue #30

**Comment by rwcarlsen** [comment]
Thanks @jbardin!

**Pull request merged**
